### ISSUE TITLE
Possible to make code publicly available?

### ISSUE THREAD

**Issue by mhwadsworth91** [VCCRI/XGSA#2]
Dear Developer,

Thank you for making this tool publicly available; I've enjoyed working through the example provided and I am excited to test on my own data.

In the github example, It's my understanding that it specifically focuses on comparing mouse developmental cardiac genes to Zebrafish Gene Ontology. While this is a very useful walkthrough, I'm curious about how I could apply this method to compare differential-expressed genes (DEGs) between cell types of interest from two different species (e.g., CD4 T Cells found in both Mouse and Human). I think this would require using XGSA in conjunction with MCM (as you show in figure 6 of the paper). If so, would you mind posting the analysis code used to generate figure 6? It would be extremely helpful to regenerate your figure because it would help me better understand the proper implementation of the code.

Thank you for your time.

Cheers, Marc

**Comment by djevic** [comment]
Code for Fig 5 (essentially the same analysis) was provided privately.
